<?php

/**
 * @file
 * Marketo Forms integration module.
 */

/**
 * Implements hook_theme().
 */
function marketo_forms_theme() {
  return [
    'marketo_form' => [
      'variables' => [
        'host'        => NULL,
        'api_key'     => NULL,
        'form_id'     => NULL,
        'description' => NULL,
        'locale'      => NULL,
      ],
    ]
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for block templates.
 */
function marketo_forms_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#plugin_id']) && $variables['elements']['#plugin_id'] == 'marketo_form') {
    if (isset($variables['elements']['#configuration']['form_id'])) {
      $suggestions[] = 'block__marketo_form__form_' . marketo_forms_safe_form_id($variables['elements']['#configuration']['form_id']);
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function marketo_forms_theme_suggestions_marketo_form(array $variables) {
  $suggestions = array();

  $form_id = trim($variables['form_id']);
  $suggestions[] = 'marketo_form__form_' . marketo_forms_safe_form_id($form_id);

  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK() for marketo_form templates.
 */
function marketo_forms_preprocess_marketo_form(&$variables) {
  $host = trim($variables['host']);
  $api_key = trim($variables['api_key']);
  $form_id = trim($variables['form_id']);

  $variables['form_id_safe'] = marketo_forms_safe_form_id($form_id);

  if (!empty($host)) {
    $variables['api_url'] = "//{$host}/js/forms2/js/forms2.js";
  }
}

function marketo_forms_safe_form_id($form_id) {
  $clean_form_id = preg_replace('/[^A-Za-z0-9_]+/xi', '_', $form_id);
  $clean_form_id = preg_replace('/_+/xi', '_', $clean_form_id);
  return $clean_form_id;
}
